### ISSUE TITLE
Attempted to load class "SeoUrlDefinition" from namespace "Shopware\Core\Framework\Seo\SeoUrl\". Did you forget a "use" statement for another namespace?

### ISSUE THREAD

**Issue by alexSanni** [elkmod/SwagShopwarePwa#36]
Hi,

when I request the /vsf/routes endpoint than I get following error:

`Attempted to load class \"SeoUrlDefinition\" from namespace \"Shopware\\Core\\Framework\\Seo\\SeoUrl\".\nDid you forget a \"use\" statement for another namespace?`

<img width="1920" alt="Bildschirmfoto 2020-03-03 um 16 57 52" src="https://user-images.githubusercontent.com/1966644/75793841-3b402000-5d70-11ea-8c04-12bb57dde334.png">

What could be wrong?

**Comment by elkmod** [comment]
Hi Alex,

I suppose the namespace has actually been moved. We're clearing up on whether we still need this endpoint - as of SW6.2 (and current platform-master) we do have a dedicated endpoint for routes, so this particular endpoint might become obsolete anyway.

Dom
