### ISSUE TITLE
Support for Shopware 6.3

### ISSUE THREAD

**Issue by martin-pixelstore** [elkmod/SwagShopwarePwa#52]
I understand that 6.1 is no longer supported, but isn't 6.3.x supported either? When I'm installing the plugin I get `Required plugin/package "shopware/core v6.2.*" does not match installed version 6.3.0.0.`

**Comment by elkmod** [comment]
Thanks for noting that @martin-pixelstore we will release a 6.3 version shortly. In the meanwhile you can still use the other installation path and manually adjust the requirement.

**Comment by elkmod** [comment]
@martin-pixelstore we've just released v0.1.4 which is also compatible with Shopware 6.3.*

Please keep an eye on the corresponding update for [shopware-pwa](https://github.com/DivanteLtd/shopware-pwa/pull/1012)  until it's merged, then you can update your PWA instance.
