### ISSUE TITLE
Could not locate "~/shopware-pwa.config.js"

### ISSUE THREAD

**Issue by jissereitsma** [elkmod/SwagShopwarePwa#67]
In my current PWA build, I was unable to locate "~/shopware-pwa.config.js". Somehow the default NuxtJS alias `~` (and for that matter, `@` as well) didn't work. I was able to fix this quite easily by merging the following in my `nuxt.config.js`:

```js
import path from 'path';
export default {
  build: {
    extend (config) {
      config.resolve.alias['~'] = path.resolve('.')
    }
  }
}
```

But is this a known issue?

**Comment by elkmod** [comment]
Hey Jisse, sorry for only getting back now - I must have missed this issue! This is only the repository for the Shopware extension, hence I'm moving the issue to the shopware-pwa repository :)

**Comment by elkmod** [comment]
Which did not work as easy as I thought.. Would you mind re-creating the [issue over here](https://github.com/vuestorefront/shopware-pwa/issues), if it's still a thing?
