### ISSUE TITLE
Console crashes in Shopware 6.4.3.x

### ISSUE THREAD

**Issue by Floddy** [elkmod/SwagShopwarePwa#88]
See PR:
https://github.com/elkmod/SwagShopwarePwa/pull/87
I also see now that there already was a PR, made in a slightly different way:
https://github.com/elkmod/SwagShopwarePwa/pull/84

**Comment by develth** [comment]
This solves the issue.
Would be nice to merge it @elkmod @xeno010 @bogdan-racz 

Thanks!

**Comment by elkmod** [comment]
Closing this, because it was already resolved with #84 - thank you very much for the contribution @Floddy.
